# Generated by Django 5.1.2 on 2024-11-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_dz_123', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(default=0),
        ),
    ]
